/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f9f9f9",
        "on-tertiary-fixed": "#1b1b1d",
        "primary": "#004e9f",
        "outline-variant": "#c1c6d5",
        "background-off-white": "#F5F5F7",
        "surface-tint": "#005cba",
        "tertiary-container": "#69686a",
        "on-secondary-container": "#616365",
        "tertiary-fixed-dim": "#c8c6c8",
        "surface-container": "#eeeeee",
        "on-tertiary-container": "#ebe8ea",
        "tertiary": "#515052",
        "surface-container-low": "#f3f3f4",
        "primary-container": "#0066cc",
        "inverse-surface": "#2f3131",
        "secondary-fixed": "#e2e2e4",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f0f1f1",
        "tertiary-fixed": "#e4e2e4",
        "outline": "#727784",
        "surface-variant": "#e2e2e2",
        "on-background": "#1a1c1c",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#c6c6c8",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#414753",
        "on-primary-fixed": "#001b3e",
        "secondary-container": "#dfdfe1",
        "surface-container-high": "#e8e8e8",
        "on-secondary-fixed-variant": "#454749",
        "inverse-primary": "#aac7ff",
        "on-primary-fixed-variant": "#00458e",
        "secondary": "#5d5e60",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "surface": "#f9f9f9",
        "soft-gray": "#86868B",
        "on-primary-container": "#dfe8ff",
        "on-tertiary-fixed-variant": "#474649",
        "surface-dim": "#dadada",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e2e2e2",
        "deep-charcoal": "#1D1D1F",
        "on-surface": "#1a1c1c",
        "on-secondary-fixed": "#1a1c1d",
        "background": "#f9f9f9",
        "primary-fixed": "#d7e3ff",
        "system-blue": "#0066CC",
        "primary-fixed-dim": "#aac7ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "120px",
        "gutter": "24px",
        "container-max": "1200px",
        "margin-desktop": "80px",
        "margin-mobile": "20px",
        "unit": "8px"
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "caption": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "body-lg": ["19px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "caption": ["12px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "400"}],
        "display-lg": ["56px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body-md": ["17px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "display-lg-mobile": ["40px", {"lineHeight": "1.1", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
